name: Publish design system on Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-pages-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Add robots.txt
        run: |
          touch storybook-static/robots.txt
          echo "User-agent: *" >> storybook-static/robots.txt
          echo "Disallow: /" >> storybook-static/robots.txt

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
