name: Deploy design system to Chromatic

on:
  workflow_dispatch:

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install --workspace=@wineries/design-system

      - name: Publish to Chromatic 🚀
        uses: chromaui/action@v1

        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'design-system:build'
